export const CRITERIAS_ORDER = new Map([
    "fw",
    "fw_woman",
    "fw_man",
    "dance_figs",
    "composition",
    "mistakes",
    "a1",
    "a2",
    "a3",
    "a4",
    "a5",
    "a6",
    "a7",
    "a8",
].map((value, idx) => [value, idx]));
